#!/usr/bin/env node
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(dirname, '..');

const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'));
const runtimeDeps = Object.keys(pkg.dependencies ?? {}).sort();

function readDepMeta(name) {
  const segments = name.split('/');
  const candidates = [
    path.join(root, 'node_modules', ...segments, 'package.json'),
  ];
  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      try {
        return JSON.parse(readFileSync(candidate, 'utf8'));
      } catch {
        return null;
      }
    }
  }
  return null;
}

function pickLicense(meta) {
  if (!meta) return 'UNKNOWN';
  if (typeof meta.license === 'string') return meta.license;
  if (Array.isArray(meta.licenses)) {
    return meta.licenses.map((entry) => entry?.type ?? entry).filter(Boolean).join(' OR ') || 'UNKNOWN';
  }
  if (meta.license && typeof meta.license === 'object') {
    return meta.license.type ?? 'UNKNOWN';
  }
  return 'UNKNOWN';
}

function pickHomepage(meta) {
  if (!meta) return undefined;
  if (typeof meta.homepage === 'string' && meta.homepage.length > 0) return meta.homepage;
  if (typeof meta.repository === 'string') return meta.repository;
  if (meta.repository && typeof meta.repository.url === 'string') {
    return meta.repository.url.replace(/^git\+/, '').replace(/\.git$/, '');
  }
  return undefined;
}

const entries = runtimeDeps.map((name) => {
  const meta = readDepMeta(name);
  return {
    name,
    version: meta?.version ?? (pkg.dependencies[name] ?? ''),
    license: pickLicense(meta),
    homepage: pickHomepage(meta),
  };
});

const banner = `// AUTO-GENERATED by scripts/gen-acks.mjs — do not edit.\n// Regenerated each \`npm run gen:acks\` / \`npm run build:desktop\`.\n`;

const body = `export interface AcknowledgementEntry {\n  readonly name: string;\n  readonly version: string;\n  readonly license: string;\n  readonly homepage?: string;\n}\n\nexport const ACKNOWLEDGEMENTS: readonly AcknowledgementEntry[] = ${JSON.stringify(entries, null, 2)};\n`;

const outPath = path.join(root, 'src', 'desktop', 'runtime', 'acknowledgements.generated.ts');
writeFileSync(outPath, banner + '\n' + body);
console.log(`Wrote ${entries.length} acknowledgements to ${path.relative(root, outPath)}`);
